# Generated by Django 5.1.2 on 2025-07-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companyprofile_logo_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
