"""Initial migration

Revision ID: 2ab9a83e0286
Revises: 
Create Date: 2025-03-22 10:40:48.430782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ab9a83e0286'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_listings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_company_profiles_email', table_name='company_profiles')
    op.drop_index('ix_company_profiles_id', table_name='company_profiles')
    op.drop_table('company_profiles')
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'experience',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portfolio', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('user_type', mysql.VARCHAR(length=10), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'experience',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'skills')
    op.create_table('company_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='company_profiles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_company_profiles_id', 'company_profiles', ['id'], unique=False)
    op.create_index('ix_company_profiles_email', 'company_profiles', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('skills_required', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('salary', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], name='jobs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
