"""Update company_profiles schema

Revision ID: e066fdb8caaa
Revises: 49e8a516fdf9
Create Date: 2025-05-05 18:54:07.169374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e066fdb8caaa'
down_revision: Union[str, None] = '49e8a516fdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('job_listings', sa.JSON(), nullable=True))
    op.alter_column('company_profiles', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company_profiles', 'industry',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company_profiles', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('company_profiles', 'size')
    op.drop_column('company_profiles', 'profile_picture')
    op.drop_column('company_profiles', 'job_posting_guidelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('job_posting_guidelines', mysql.TEXT(), nullable=True))
    op.add_column('company_profiles', sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('company_profiles', sa.Column('size', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('company_profiles', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('company_profiles', 'industry',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('company_profiles', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('company_profiles', 'job_listings')
    # ### end Alembic commands ###
